export const USER_PREFERENCES_AUTHENTICATED_INSERT_COLUMNS = [
  'user_id',
  'preferred_ai_model',
  'analytics_timezone',
  'updated_at',
] as const;

export const USER_PREFERENCES_AUTHENTICATED_UPDATE_COLUMNS = [
  'preferred_ai_model',
  'analytics_timezone',
  'updated_at',
] as const;

export const USER_EMAIL_NOTIFICATION_SETTINGS_AUTHENTICATED_INSERT_COLUMNS = [
  'user_id',
  'unsubscribe_all_optional_emails',
  'updated_at',
] as const;

export const USER_EMAIL_NOTIFICATION_SETTINGS_AUTHENTICATED_UPDATE_COLUMNS = [
  'unsubscribe_all_optional_emails',
  'updated_at',
] as const;

export const USER_EMAIL_NOTIFICATION_PREFERENCES_AUTHENTICATED_INSERT_COLUMNS =
  ['user_id', 'category', 'enabled', 'unsubscribed_at', 'updated_at'] as const;

export const USER_EMAIL_NOTIFICATION_PREFERENCES_AUTHENTICATED_UPDATE_COLUMNS =
  ['enabled', 'unsubscribed_at', 'updated_at'] as const;

export const USER_PREFERENCES_AUTHENTICATED_INSERT_COLUMNS_SQL =
  USER_PREFERENCES_AUTHENTICATED_INSERT_COLUMNS.join(', ');

export const USER_PREFERENCES_AUTHENTICATED_UPDATE_COLUMNS_SQL =
  USER_PREFERENCES_AUTHENTICATED_UPDATE_COLUMNS.join(', ');

export const USER_EMAIL_NOTIFICATION_SETTINGS_AUTHENTICATED_INSERT_COLUMNS_SQL =
  USER_EMAIL_NOTIFICATION_SETTINGS_AUTHENTICATED_INSERT_COLUMNS.join(', ');

export const USER_EMAIL_NOTIFICATION_SETTINGS_AUTHENTICATED_UPDATE_COLUMNS_SQL =
  USER_EMAIL_NOTIFICATION_SETTINGS_AUTHENTICATED_UPDATE_COLUMNS.join(', ');

export const USER_EMAIL_NOTIFICATION_PREFERENCES_AUTHENTICATED_INSERT_COLUMNS_SQL =
  USER_EMAIL_NOTIFICATION_PREFERENCES_AUTHENTICATED_INSERT_COLUMNS.join(', ');

export const USER_EMAIL_NOTIFICATION_PREFERENCES_AUTHENTICATED_UPDATE_COLUMNS_SQL =
  USER_EMAIL_NOTIFICATION_PREFERENCES_AUTHENTICATED_UPDATE_COLUMNS.join(', ');
