codecov:
  require_ci_to_pass: true
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        only_pulls: true
  precision: 2
  round: down
  range: 50..100
ignore:
  - 'tests/**'
  - '**/*.d.ts'
  - 'src/lib/db/**'
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
