services:
  postgres:
    image: postgres:17
    command: '-d 1'
    shm_size: 128mb
    volumes:
      - atlaris_dev_data:/var/lib/postgresql/data
    ports:
      - '54331:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=atlaris_dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  atlaris_dev_data:
