export const API_ERROR_CODES = {
  FREE_PLAN_ALLOWANCE_USED: 'FREE_PLAN_ALLOWANCE_USED',
  FREE_PLAN_GENERATION_IN_PROGRESS: 'FREE_PLAN_GENERATION_IN_PROGRESS',
  FREE_PLAN_SELECTION_REQUIRED: 'FREE_PLAN_SELECTION_REQUIRED',
  PLAN_ENTITLEMENT_REQUIRED: 'PLAN_ENTITLEMENT_REQUIRED',
  PLAN_REGENERATION_NOT_INCLUDED: 'PLAN_REGENERATION_NOT_INCLUDED',
  REGENERATION_QUOTA_EXCEEDED: 'REGENERATION_QUOTA_EXCEEDED',
  PLAN_DURATION_LIMIT_EXCEEDED: 'PLAN_DURATION_LIMIT_EXCEEDED',
  MODEL_NOT_AVAILABLE_FOR_OPERATION: 'MODEL_NOT_AVAILABLE_FOR_OPERATION',
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export const API_ERROR_HTTP_STATUS: Record<ApiErrorCode, 403 | 409 | 429> = {
  FREE_PLAN_ALLOWANCE_USED: 403,
  FREE_PLAN_GENERATION_IN_PROGRESS: 409,
  FREE_PLAN_SELECTION_REQUIRED: 409,
  PLAN_ENTITLEMENT_REQUIRED: 403,
  PLAN_REGENERATION_NOT_INCLUDED: 403,
  REGENERATION_QUOTA_EXCEEDED: 429,
  PLAN_DURATION_LIMIT_EXCEEDED: 403,
  MODEL_NOT_AVAILABLE_FOR_OPERATION: 403,
};
