#!/usr/bin/env bash
set -Eeuo pipefail

readonly LOG_PREFIX='[codex-1password]'
readonly GENERATED_MARKER='# Generated by scripts/agents/codex-1password-env.sh from 1Password Environment'

log() {
  printf '%s %s\n' "$LOG_PREFIX" "$*"
}

fail() {
  printf '%s ERROR: %s\n' "$LOG_PREFIX" "$*" >&2
  exit 1
}

run_as_root() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  elif command -v sudo >/dev/null 2>&1; then
    sudo "$@"
  else
    fail 'Need root permissions, but neither root nor sudo is available.'
  fi
}

repo_root() {
  git rev-parse --show-toplevel 2>/dev/null || pwd
}

install_1password_cli() {
  if command -v op >/dev/null 2>&1 && op environment read --help >/dev/null 2>&1; then
    log "1Password CLI already installed: $(op --version)"
    return
  fi

  command -v apt-get >/dev/null 2>&1 ||
    fail "1Password CLI is missing or lacks 'op environment read'; automatic install only supports Debian/Ubuntu containers with apt-get."

  log 'Installing 1Password CLI...'

  run_as_root apt-get update
  run_as_root env DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates \
    curl \
    gnupg

  curl -fsSL https://downloads.1password.com/linux/keys/1password.asc |
    run_as_root gpg --batch --yes --dearmor \
      --output /usr/share/keyrings/1password-archive-keyring.gpg

  printf 'deb [arch=%s signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/%s stable main\n' \
    "$(dpkg --print-architecture)" \
    "$(dpkg --print-architecture)" |
    run_as_root tee /etc/apt/sources.list.d/1password.list >/dev/null

  run_as_root mkdir -p /etc/debsig/policies/AC2D62742012EA22/
  curl -fsSL https://downloads.1password.com/linux/debian/debsig/1password.pol |
    run_as_root tee /etc/debsig/policies/AC2D62742012EA22/1password.pol >/dev/null

  run_as_root mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
  curl -fsSL https://downloads.1password.com/linux/keys/1password.asc |
    run_as_root gpg --batch --yes --dearmor \
      --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

  run_as_root apt-get update
  run_as_root env DEBIAN_FRONTEND=noninteractive apt-get install -y 1password-cli

  command -v op >/dev/null 2>&1 || fail '1Password CLI install completed, but op is not on PATH.'
  op environment read --help >/dev/null 2>&1 ||
    fail "Installed 1Password CLI does not support 'op environment read'. Update the CLI before using this setup script."

  log "Installed 1Password CLI: $(op --version)"
}

environment_id() {
  local id="${OP_ENVIRONMENT_ID:-}"
  [[ -n "$id" ]] ||
    fail 'Missing OP_ENVIRONMENT_ID. Set it as a Codex cloud secret with your 1Password Environment ID.'
  printf '%s' "$id"
}

assert_service_account_auth() {
  [[ -n "${OP_SERVICE_ACCOUNT_TOKEN:-}" ]] ||
    fail 'Missing OP_SERVICE_ACCOUNT_TOKEN. Set it as a Codex cloud secret.'

  export OP_SERVICE_ACCOUNT_TOKEN

  # 1Password Connect auth takes precedence over service account auth.
  unset OP_CONNECT_HOST
  unset OP_CONNECT_TOKEN

  log 'Verifying 1Password service account auth...'
  op user get --me >/dev/null ||
    fail '1Password service account auth failed. Check OP_SERVICE_ACCOUNT_TOKEN and service account status.'
}

assert_env_payload() {
  local file=$1

  grep -Eq '^[A-Za-z_][A-Za-z0-9_]*=' "$file" ||
    fail '1Password Environment output did not contain dotenv-style KEY=value entries.'
}

write_env_file() {
  local root env_file env_id raw_file final_file old_umask
  root="$(repo_root)"
  env_file="${AGENT_ENV_FILE:-$root/.env.local}"
  env_id="$(environment_id)"
  raw_file=''
  final_file=''

  cleanup() {
    [[ -n "${raw_file:-}" && -f "$raw_file" ]] && rm -f "$raw_file"
    [[ -n "${final_file:-}" && -f "$final_file" ]] && rm -f "$final_file"
  }
  trap cleanup EXIT

  if [[ -f "$env_file" ]] &&
    ! head -n 1 "$env_file" | grep -qxF "$GENERATED_MARKER" &&
    [[ "${AGENT_ENV_OVERWRITE:-0}" != '1' ]]; then
    fail "$env_file already exists and was not generated by this script. Set AGENT_ENV_OVERWRITE=1 to replace it."
  fi

  mkdir -p "$(dirname "$env_file")"

  old_umask="$(umask)"
  umask 077
  raw_file="$(mktemp)"
  final_file="$(mktemp)"
  umask "$old_umask"

  log 'Reading 1Password Environment...'
  op environment read "$env_id" >"$raw_file" ||
    fail 'Failed to read the 1Password Environment. Check OP_ENVIRONMENT_ID and service account access.'

  assert_env_payload "$raw_file"

  {
    printf '%s\n' "$GENERATED_MARKER"
    printf '%s\n' '# Do not commit this file. Generated inside Codex setup.'
    printf '\n'
    cat "$raw_file"
  } >"$final_file"

  mv "$final_file" "$env_file"
  final_file=''
  chmod 600 "$env_file"

  log "Wrote 1Password Environment to $env_file"
}

main() {
  install_1password_cli
  assert_service_account_auth
  write_env_file
  log 'Done.'
}

main "$@"
