#!/usr/bin/env bash
# Install the keychain-backed `op` wrapper and user-level launcher config.
set +x
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
TEMPLATE="$SCRIPT_DIR/op-atlaris-wrapper.sh"
KEYCHAIN_SERVICE='atlaris.op-service-account'
KEYCHAIN_ACCOUNT='atlaris'

usage() {
  printf 'Usage: scripts/dev/install-local-op.sh [--environment-id ID] [--token-stdin] [--op-path PATH] [--force-config]\n' >&2
}

fail() {
  printf 'FAIL %s\n' "$*" >&2
  exit 1
}

environment_id=
op_path=
token_stdin=0
force_config=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --environment-id)
      [[ $# -ge 2 ]] || fail '--environment-id requires a value'
      environment_id=$2
      shift 2
      ;;
    --op-path)
      [[ $# -ge 2 ]] || fail '--op-path requires a value'
      op_path=$2
      shift 2
      ;;
    --token-stdin)
      token_stdin=1
      shift
      ;;
    --force-config)
      force_config=1
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done

[[ -f "$TEMPLATE" ]] || fail "Missing wrapper template: $TEMPLATE"

wrapper_path=${OP_WRAPPER_PATH:-$HOME/.local/bin/op-atlaris}
config_path=${ATLARIS_DEV_CONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/atlaris/dev.sh}

resolve_op() {
  if [[ -n "$op_path" ]]; then
    printf '%s' "$op_path"
    return
  fi
  local directory candidate
  local -a directories
  IFS=: read -r -a directories <<< "$PATH"
  for directory in "${directories[@]}"; do
    candidate="$directory/op"
    if [[ -x "$candidate" && "$candidate" != "$wrapper_path" ]]; then
      printf '%s' "$candidate"
      return
    fi
  done
  return 1
}

real_op=$(resolve_op) || fail '1Password CLI (op) not found on PATH. Install op or pass --op-path.'
[[ -x "$real_op" ]] || fail "1Password CLI is not executable: $real_op"
[[ "$real_op" != "$wrapper_path" ]] || fail 'Refusing to point the wrapper at itself. Pass --op-path to the real op binary.'
printf 'OK   using 1Password CLI at %s\n' "$real_op"

if [[ "$token_stdin" -eq 1 ]]; then
  command -v security >/dev/null 2>&1 || fail 'macOS `security` is required to store the service-account token in the keychain.'
  token=
  if [[ -t 0 ]]; then
    printf 'Paste the service-account token, then press Enter. Input is hidden.\n' >&2
    IFS= read -r -s token || true
    printf '\n' >&2
  else
    printf 'Reading service-account token from stdin...\n' >&2
    IFS= read -r token || true
  fi
  [[ -n "$token" ]] || fail 'Read an empty token from stdin. Create a scoped service account, then paste it and press Enter.'
  printf 'Storing the token in the keychain (approve the macOS prompt if one appears)...\n' >&2
  security add-generic-password -U -s "$KEYCHAIN_SERVICE" -a "$KEYCHAIN_ACCOUNT" -w "$token" >/dev/null
  unset token
  printf 'OK   stored service-account token in the keychain (service %s)\n' "$KEYCHAIN_SERVICE"
fi

mkdir -p "$(dirname "$wrapper_path")"
umask 077
tmp_wrapper=$(mktemp "${wrapper_path}.XXXXXX")
sed "s|__OP_REAL_EXECUTABLE__|${real_op}|g" "$TEMPLATE" >"$tmp_wrapper"
chmod 700 "$tmp_wrapper"
mv "$tmp_wrapper" "$wrapper_path"

if [[ -f "$config_path" && "$force_config" -ne 1 ]]; then
  printf 'OK   left existing launcher config in place: %s\n' "$config_path"
  printf '     Set OP_EXECUTABLE=%s and OP_ENVIRONMENT_ID there if needed.\n' "$wrapper_path"
else
  mkdir -p "$(dirname "$config_path")"
  cat >"$config_path" <<EOF
# Machine-local Atlaris launcher config. Not a secret file.
# Generated by scripts/dev/install-local-op.sh
: "\${OP_EXECUTABLE:=$wrapper_path}"
: "\${OP_ENVIRONMENT_ID:=$environment_id}"
EOF
  chmod 600 "$config_path"
  printf 'OK   wrote launcher config: %s\n' "$config_path"
fi

printf 'OK   installed op wrapper: %s -> %s\n' "$wrapper_path" "$real_op"
printf '     Token stays in the keychain. Portless/Next never receive it.\n'
if [[ -z "$environment_id" ]]; then
  printf '     Set OP_ENVIRONMENT_ID in %s or your shell.\n' "$config_path"
fi
