name: CI - Prod (production env)

on:
  push:
    branches: [prod]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  post-deploy-verify:
    name: Post-Deploy Verify
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 5
    steps:
      - name: Health Check
        run: |
          if [ -z "${{ vars.PROD_HEALTHCHECK_URL }}" ]; then
            echo "PROD_HEALTHCHECK_URL not set; failing to ensure configuration."
            exit 1
          fi
          timeout=300
          start=$(date +%s)
          while [ $(( $(date +%s) - start )) -lt $timeout ]; do
            if curl -f -s --max-time 10 "${{ vars.PROD_HEALTHCHECK_URL }}/api/health"; then
              echo "Health check passed."
              exit 0
            fi
            echo "Health check failed; retrying in 10s..."
            sleep 10
          done
          echo "Health check timed out after ${timeout}s"
          exit 1
