name: Tests

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase (Docker)
        run: supabase start

      - name: Create .env.test from GitHub environment
        run: |
          # Extract JWT secret from running Supabase instance
          JWT_SECRET=$(supabase status | grep -oP 'JWT secret: \K.*')
          echo "::add-mask::$JWT_SECRET"

          cat > .env.test << EOF
          NODE_ENV=test
          DATABASE_URL=${{ vars.DATABASE_URL }}
          NEXT_PUBLIC_SUPABASE_URL=${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${{ vars.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
          SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          TEST_JWT_SECRET=${JWT_SECRET}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
          CLERK_ISSUER=${{ secrets.CLERK_ISSUER }}
          DEV_CLERK_USER_ID=${{ secrets.DEV_CLERK_USER_ID }}
          DEV_CLERK_USER_EMAIL=${{ secrets.DEV_CLERK_USER_EMAIL }}
          DEV_CLERK_USER_NAME=${{ secrets.DEV_CLERK_USER_NAME }}
          AI_PROVIDER=${{ vars.AI_PROVIDER }}
          MOCK_GENERATION_DELAY_MS=${{ vars.MOCK_GENERATION_DELAY_MS }}
          MOCK_GENERATION_FAILURE_RATE=${{ vars.MOCK_GENERATION_FAILURE_RATE }}
          EOF

      - name: Apply migrations with Drizzle
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
        run: pnpm db:push

      - name: Run test suite
        run: pnpm test

      - name: Cleanup test env file
        if: always()
        run: |
          shred -u .env.test 2>/dev/null || rm -f .env.test || true

      - name: Stop Supabase
        if: always()
        run: supabase stop --no-backup

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            coverage/
            .next/
          retention-days: 7
